<h1>POLÍTICA DE PRIVACIDAD</h1>
<p>En cumplimiento del artículo 6º de la ley 25.326 (Ley de protección de datos personales) debes saber que los datos facilitados a Petit Shop S.R.L. para el uso del website son necesarios para establecer la relación contractual entre el cliente y la empresa y serán tratados únicamente para las operaciones relativas al cumplimiento de las Reglas, encuestas, suscripciones, ofertas y cualquier otra acción comercial, en total cumplimiento de las normativas aplicables.</p>
<p>El usuario toma conocimiento de la existencia de un banco de datos donde se almacena su información personal, con sede en Petit Shop S.R.L., única responsable del mismo y, en ningún caso, los datos facilitados serán entregados a terceros, siendo dicha información totalmente confidencial entre el usuario y Petit Shop S.R.L., salvo que la información le sea requerida a Petit Shop S.R.L. por una resolución judicial o por una autoridad gubernamental competente.</p>
<p>Toda la información que nos proporciones deberá ser verdadera, exacta y completa. El usuario es único y exclusivo responsable de la información que brinda mediante el uso del website. En tal sentido, el usuario será único y exclusivo responsable respecto de las consecuencias que genere cualquier exactitud o falsedad de la información brindada.</p>
<p>El usuario toma conocimiento de la facultad de ejercer el derecho de acceso a sus datos personales en forma gratuita a intervalos no inferiores a seis meses, salvo que acredite un interés legítimo al efecto y, asimismo, que tiene derecho de ser procedente a rectificar y/o suprimir dichos datos. La Dirección Nacional de Protección de Datos Personales es el órgano de control de la Ley 25.326 y tiene la atribución de atender las denuncias y reclamos que se interpongan en relación al incumplimiento de las normas sobre protección de datos personales (arts. 14, 15 y 16 de la Ley 25.326 y Disposición 10/08 de la DNPDP).</p>
<p>Si tenés algún comentario o pregunta acerca de esta Política de Privacidad o sobre su información personal, por favor, contáctese a la siguiente dirección de e-mail: info@petitShop.com</p>
<h1>COMPRA DE PRODUCTOS</h1>
<p>La compra de productos o servicios ofrecidos en el website se encuentra sujeta a disponibilidad de stock. Las fotos de los productos son ilustrativas. Los productos, servicios, características técnicas, precios, disponibilidad y ofertas contenidas en este website pueden variar sin previo aviso.</p>
<h1>PRECIOS</h1>
<p>Todos los precios incluyen IVA. Los precios de los artículos ofrecidos en www.petit-shop.herokuapp.com pueden sufrir modificaciones al momento de realizarse la facturación de los mismos. Los precios de los productos ofrecidos en www.petit-shop.herokuapp.com se facturan con el valor ofrecido al momento de cerrar la compra. Las promociones no son acumulables, a excepción de aquellas en que se aclare expresamente que sí lo son.</p>
<h1>CONDICIONES DE PAGO</h1>
<p>Las ofertas y promociones publicadas son válidas para compras por venta telefónica o ventas por internet abonadas dentro del período de vigencia de las mismas. Usted puede pagar su compra con dinero en efectivo, transferencia bancaria, tarjetas de crédito y débito. El pago en efectivo se admite únicamente en moneda nacional al momento de la entrega. En el caso de que la entrega no se realice el día acordado por causas ajenas al cliente, se respetarán tanto el precio como la promoción. Para el pago con tarjeta de crédito online, www.petit-shop.herokuapp.com proporciona un ambiente protegido para que sus clientes puedan operar de manera segura, utilizando prácticas de seguridad empleadas en el mercado electrónico internacional. Se tomará como fecha de cobro la elegida por el cliente al momento de cerrar la compra. Ante la imposibilidad de concretar la operación, un empleado se comunicará con vos para definir un nuevo pago. Ante cualquier duda, podés solicitar asistencia llamando al 0810-888-PETS (7387), de lunes a sábados de 9 a 20 hs o enviándonos un email a ventas@petitShop.com</p>
<h1>INDEMNIDAD</h1>
<p>El usuario se obliga en forma expresa e irrevocable a mantener absolutamente indemne a Petit Shop S.R.L. respecto de cualquier reclamo y/o demanda y/o sanción extrajudicial, administrativa o judicial de cualquier tercero, derivada del uso del website, o en caso de verificarse la existencia de multas y/o deudas de cualquier tipo generadas por el usuario o la actividad del mismo realizada en o mediante el website.</p>
<h1>DERECHOS DE MARCA, PUBLICIDAD Y PROPIEDAD INTELECTUAL</h1>
<p>Todos los elementos que forman parte del website solo tiene como destino la comercialización de productos por parte de Petit Shop S.R.L. y se encuentra prohibida cualquier reproducción, modificación o distribución de los mismos. Todos los comentarios, sugerencias o ideas suministradas por el usuario serán propiedad de Petit Shop S.R.L.</p>
<p>Todos los derechos reservados. Petit Shop S.R.L., con domicilio legal en Bulnes 984 CABA, Buenos Aires, Argentina.</p>
<h1>POLÍTICA DE DEVOLUCIÓN</h1>
<p>El cliente podrá efectuar el reembolso del pedido por aquellos productos que no estén en condiciones o no se corresponda con lo efectivamente comprado, realizando la inmediata devolución al chofer.</p>
<p>Si el producto entregado tiene defectos o daños, dentro de las 48 hs. posteriores a su recepción, podrá tramitar su reclamo telefónicamente.</p>